#!/usr/bin/env bash
# displaying time for 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ];
do
	minutes=1
	echo "Hour:" $hour
	while [ $minutes -lt 60 ];
	do
		echo $minutes
		((minutes++))
	done
	((hour++))
done